spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: user
    password: user
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083
